"""
ai-skills SDK — AutoGen Exporter
Converts a skill.yaml file into a native AutoGen FunctionTool.

Usage:
    python exporters/autogen.py path/to/skill.yaml
    python exporters/autogen.py path/to/skill.yaml --output my_tool.py
"""

import yaml
import argparse
from pathlib import Path


def export_autogen(skill_path: str, output_path: str = None) -> str:
    with open(skill_path) as f:
        data = yaml.safe_load(f)

    skill = data["skill"]
    execution = skill["execution"]
    exec_type = execution["type"]

    skill_id = skill["id"].replace("-", "_")
    class_name = "".join(word.capitalize() for word in skill["id"].split("-"))
    inputs = skill.get("inputs", [])
    outputs = skill.get("outputs", [])
    description = skill.get("description", "").strip().replace("\n", " ")
    name = skill.get("name", skill_id)
    version = skill.get("version", "1.0.0")

    # Build function signature
    sig_parts = []
    for inp in inputs:
        py_type = _to_python_type(inp.get("type", "string"))
        required = inp.get("required", False)
        default = inp.get("default")
        if required:
            sig_parts.append(f'{inp["name"]}: {py_type}')
        else:
            if default is not None:
                sig_parts.append(f'{inp["name"]}: {py_type} = {repr(default)}')
            else:
                sig_parts.append(f'{inp["name"]}: Optional[{py_type}] = None')

    signature = ", ".join(sig_parts)

    # Build docstring
    docstring_lines = [description, ""]
    docstring_lines.append("Args:")
    for inp in inputs:
        req = "(required)" if inp.get("required") else "(optional)"
        docstring_lines.append(f'    {inp["name"]}: {inp.get("description", "")} {req}')
    docstring_lines.append("")
    docstring_lines.append("Returns:")
    for out in outputs:
        docstring_lines.append(f'    {out["name"]}: {out.get("description", "")}')
    docstring = "\n    ".join(docstring_lines)

    # Build function body
    if exec_type == "prompt":
        func_body = _build_prompt_body(execution, inputs)
    elif exec_type == "tool_call":
        func_body = _build_tool_call_body(execution)
    elif exec_type == "code":
        func_body = _build_code_body(execution)
    else:
        func_body = f'    raise NotImplementedError("Execution type \'{exec_type}\' requires manual implementation")'

    # Build optional type hints import
    has_optional = any(not inp.get("required", False) and inp.get("default") is None for inp in inputs)
    optional_import = "from typing import Optional, Any\n" if has_optional else "from typing import Any\n"

    code = f'''"""
Auto-generated by ai-skills SDK
Skill: {name} v{version}
Source: {skill_path}

DO NOT EDIT — regenerate using:
    python exporters/autogen.py {skill_path}
"""

{optional_import}
from autogen_core.tools import FunctionTool


def {skill_id}({signature}) -> dict:
    """
    {docstring}
    """
{func_body}


# Register as an AutoGen FunctionTool
{skill_id}_tool = FunctionTool(
    {skill_id},
    description="{description}",
    name="{skill_id}",
)


# ── Usage ────────────────────────────────────────────────────────────────────
#
# from autogen_agentchat.agents import AssistantAgent
# from autogen_ext.models.openai import OpenAIChatCompletionClient
#
# model_client = OpenAIChatCompletionClient(model="gpt-4o")
#
# agent = AssistantAgent(
#     name="assistant",
#     model_client=model_client,
#     tools=[{skill_id}_tool],
# )
#
# import asyncio
# result = asyncio.run(agent.run(task="Use the {skill_id} skill to ..."))
# ─────────────────────────────────────────────────────────────────────────────
'''

    if output_path:
        Path(output_path).write_text(code, encoding="utf-8")
        print(f"Exported to: {output_path}")
    else:
        print(code)

    return code


def _to_python_type(aiskills_type: str) -> str:
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
        "file": "str",
        "image": "str",
        "any": "Any",
    }.get(aiskills_type, "str")


def _build_prompt_body(execution: dict, inputs: list) -> str:
    system_prompt = execution.get("system_prompt", "").strip()
    template = execution.get("prompt_template", "").strip()
    input_names = [inp["name"] for inp in inputs]
    format_kwargs = ", ".join(f"{n}={n}" for n in input_names)

    lines = [
        "    import openai",
        "    client = openai.OpenAI()",
        "    messages = []",
    ]
    if system_prompt:
        lines.append(f'    messages.append({{"role": "system", "content": """{system_prompt}"""}})')

    lines += [
        f'    prompt = """{template}"""',
        f"    formatted = prompt.format({format_kwargs})",
        '    messages.append({"role": "user", "content": formatted})',
        '    response = client.chat.completions.create(model="gpt-4o", messages=messages)',
        '    return {"result": response.choices[0].message.content}',
    ]
    return "\n".join(lines)


def _build_tool_call_body(execution: dict) -> str:
    endpoint = execution.get("endpoint", {})
    url = endpoint.get("url", "https://api.example.com")
    method = endpoint.get("method", "GET").lower()
    headers = endpoint.get("headers", {})
    params = endpoint.get("params", {})

    lines = [
        '    import requests',
        '    import os',
        '',
        f'    url = "{url}"',
    ]

    if headers:
        header_items = []
        for k, v in headers.items():
            v_code = _resolve_env_refs(v)
            header_items.append(f'        "{k}": {v_code},')
        lines.append('    headers = {')
        lines.extend(header_items)
        lines.append('    }')
    else:
        lines.append('    headers = {}')

    if params:
        param_items = []
        for k, v in params.items():
            v_code = _resolve_input_refs(v)
            param_items.append(f'        "{k}": {v_code},')
        lines.append('    params = {')
        lines.extend(param_items)
        lines.append('    }')
    else:
        lines.append('    params = {}')

    lines += [
        f'    response = requests.{method}(url, headers=headers, params=params)',
        '    response.raise_for_status()',
        '    return response.json()',
    ]
    return '\n'.join(lines)


def _build_code_body(execution: dict) -> str:
    code_block = execution.get("code", "pass").rstrip()
    # Indent each line of the code block to be inside the function
    indented_lines = []
    for line in code_block.split('\n'):
        if line.strip():  # non-empty line
            indented_lines.append(f'    {line}')
        else:
            indented_lines.append('')
    return '\n'.join(indented_lines)


def _resolve_env_refs(value: str) -> str:
    """Replace {env.VAR_NAME} patterns with os.environ.get('VAR_NAME')."""
    import re
    match = re.search(r'\{env\.(\w+)\}', value)
    if match:
        return f'os.environ.get("{match.group(1)}", "")'
    return repr(value)


def _resolve_input_refs(value: str) -> str:
    """Replace {input_name} with the input variable."""
    import re
    match = re.match(r'^\{(\w+)\}$', value.strip())
    if match:
        return match.group(1)
    return repr(value)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export a skill.yaml to an AutoGen FunctionTool")
    parser.add_argument("skill_path", help="Path to skill.yaml")
    parser.add_argument("--output", "-o", help="Output Python file path")
    args = parser.parse_args()
    export_autogen(args.skill_path, args.output)
