"""
ai-skills SDK — CrewAI Exporter
Converts a skill.yaml file into a native CrewAI BaseTool.

Usage:
    python exporters/crewai.py path/to/skill.yaml
    python exporters/crewai.py path/to/skill.yaml --output my_tool.py
"""

import yaml
import argparse
from pathlib import Path


def export_crewai(skill_path: str, output_path: str = None) -> str:
    with open(skill_path) as f:
        data = yaml.safe_load(f)

    skill = data["skill"]
    execution = skill["execution"]
    exec_type = execution["type"]

    skill_id = skill["id"].replace("-", "_")
    class_name = "".join(word.capitalize() for word in skill["id"].split("-")) + "Tool"
    inputs = skill.get("inputs", [])
    description = skill.get("description", "").strip().replace("\n", " ")
    name = skill.get("name", skill_id)
    version = skill.get("version", "1.0.0")

    # Build Pydantic input schema for CrewAI
    schema_fields = []
    for inp in inputs:
        py_type = _to_python_type(inp.get("type", "string"))
        required = inp.get("required", False)
        default = inp.get("default")
        desc = inp.get("description", "")

        if required:
            schema_fields.append(f'    {inp["name"]}: {py_type} = Field(..., description="{desc}")')
        else:
            if default is not None:
                py_default = repr(default)
            else:
                py_type = f"Optional[{py_type}]"
                py_default = "None"
            schema_fields.append(f'    {inp["name"]}: {py_type} = Field({py_default}, description="{desc}")')

    schema_body = "\n".join(schema_fields) if schema_fields else "    pass"

    # Build _run body
    if exec_type == "prompt":
        run_body = _build_prompt_body(execution, inputs)
    elif exec_type == "tool_call":
        run_body = _build_tool_call_body(execution)
    elif exec_type == "code":
        run_body = _build_code_body(execution)
    else:
        run_body = f'        raise NotImplementedError("Execution type \'{exec_type}\' requires manual implementation")'

    # Argument string for _run
    run_args = ", ".join(
        f'{inp["name"]}: {_to_python_type(inp.get("type", "string"))}'
        if inp.get("required")
        else f'{inp["name"]}: Optional[{_to_python_type(inp.get("type", "string"))}] = {repr(inp.get("default")) if inp.get("default") is not None else "None"}'
        for inp in inputs
    )

    has_optional = any(not inp.get("required", False) for inp in inputs)
    optional_import = ", Optional" if has_optional else ""

    code = f'''"""
Auto-generated by ai-skills SDK
Skill: {name} v{version}
Source: {skill_path}

DO NOT EDIT — regenerate using:
    python exporters/crewai.py {skill_path}
"""

from typing import Type{optional_import}
from pydantic import BaseModel, Field
from crewai.tools import BaseTool


class {class_name}Input(BaseModel):
    """Input schema for {name}"""
{schema_body}


class {class_name}(BaseTool):
    name: str = "{name}"
    description: str = "{description}"
    args_schema: Type[BaseModel] = {class_name}Input

    def _run(self, {run_args}) -> dict:
{run_body}


# ── Usage ────────────────────────────────────────────────────────────────────
#
# from crewai import Agent, Task, Crew
#
# tool = {class_name}()
#
# agent = Agent(
#     role="AI Specialist",
#     goal="Use the {name} skill effectively",
#     backstory="You are an expert at processing and analyzing information.",
#     tools=[tool],
#     verbose=True,
# )
#
# task = Task(
#     description="Use the {skill_id} tool to process the following: ...",
#     expected_output="A well-structured result",
#     agent=agent,
# )
#
# crew = Crew(agents=[agent], tasks=[task], verbose=True)
# result = crew.kickoff()
# ─────────────────────────────────────────────────────────────────────────────
'''

    if output_path:
        Path(output_path).write_text(code, encoding="utf-8")
        print(f"Exported to: {output_path}")
    else:
        print(code)

    return code


def _to_python_type(aiskills_type: str) -> str:
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
        "file": "str",
        "image": "str",
        "any": "Any",
    }.get(aiskills_type, "str")


def _build_prompt_body(execution: dict, inputs: list) -> str:
    system_prompt = execution.get("system_prompt", "").strip()
    template = execution.get("prompt_template", "").strip()
    input_names = [inp["name"] for inp in inputs]
    format_kwargs = ", ".join(f"{n}={n}" for n in input_names)

    lines = [
        "        import openai",
        "        client = openai.OpenAI()",
        "        messages = []",
    ]
    if system_prompt:
        lines.append(f'        messages.append({{"role": "system", "content": """{system_prompt}"""}})')

    lines += [
        f'        prompt = """{template}"""',
        f"        formatted = prompt.format({format_kwargs})",
        '        messages.append({"role": "user", "content": formatted})',
        '        response = client.chat.completions.create(model="gpt-4o", messages=messages)',
        '        return {"result": response.choices[0].message.content}',
    ]
    return "\n".join(lines)


def _build_tool_call_body(execution: dict) -> str:
    endpoint = execution.get("endpoint", {})
    url = endpoint.get("url", "https://api.example.com")
    method = endpoint.get("method", "GET").lower()
    headers = endpoint.get("headers", {})
    params = endpoint.get("params", {})

    lines = [
        '        import requests',
        '        import os',
        '',
        f'        url = "{url}"',
    ]

    if headers:
        header_items = []
        for k, v in headers.items():
            v_code = _resolve_env_refs(v)
            header_items.append(f'            "{k}": {v_code},')
        lines.append('        headers = {')
        lines.extend(header_items)
        lines.append('        }')
    else:
        lines.append('        headers = {}')

    if params:
        param_items = []
        for k, v in params.items():
            v_code = _resolve_input_refs(v)
            param_items.append(f'            "{k}": {v_code},')
        lines.append('        params = {')
        lines.extend(param_items)
        lines.append('        }')
    else:
        lines.append('        params = {}')

    lines += [
        f'        response = requests.{method}(url, headers=headers, params=params)',
        '        response.raise_for_status()',
        '        return response.json()',
    ]
    return '\n'.join(lines)


def _build_code_body(execution: dict) -> str:
    code_block = execution.get("code", "pass").rstrip()
    indented_lines = []
    for line in code_block.split('\n'):
        if line.strip():
            indented_lines.append(f'        {line}')
        else:
            indented_lines.append('')
    return '\n'.join(indented_lines)


def _resolve_env_refs(value: str) -> str:
    import re
    match = re.search(r'\{env\.(\w+)\}', value)
    if match:
        return f'os.environ.get("{match.group(1)}", "")'
    return repr(value)


def _resolve_input_refs(value: str) -> str:
    import re
    match = re.match(r'^\{(\w+)\}$', value.strip())
    if match:
        return match.group(1)
    return repr(value)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export a skill.yaml to a CrewAI BaseTool")
    parser.add_argument("skill_path", help="Path to skill.yaml")
    parser.add_argument("--output", "-o", help="Output Python file path")
    args = parser.parse_args()
    export_crewai(args.skill_path, args.output)
