"""
ai-skills SDK — LangChain Exporter
Converts a skill.yaml file into a native LangChain Tool.

Usage:
    python exporters/langchain.py path/to/skill.yaml
    python exporters/langchain.py path/to/skill.yaml --output my_tool.py
"""

import yaml
import argparse
from pathlib import Path


def export_langchain(skill_path: str, output_path: str = None) -> str:
    with open(skill_path) as f:
        data = yaml.safe_load(f)

    skill = data["skill"]
    execution = skill["execution"]
    exec_type = execution["type"]

    skill_id = skill["id"].replace("-", "_")
    class_name = "".join(word.capitalize() for word in skill["id"].split("-")) + "Tool"
    inputs = skill.get("inputs", [])
    description = skill.get("description", "").strip().replace("\n", " ")

    # Build input schema
    input_fields = []
    for inp in inputs:
        py_type = _to_python_type(inp.get("type", "string"))
        required = inp.get("required", False)
        default = inp.get("default")
        desc = inp.get("description", "")

        if required:
            input_fields.append(f'    {inp["name"]}: {py_type} = Field(..., description="{desc}")')
        else:
            if default is not None:
                default_repr = repr(default)
            else:
                py_type = f"Optional[{py_type}]"
                default_repr = "None"
            input_fields.append(f'    {inp["name"]}: {py_type} = Field({default_repr}, description="{desc}")')

    input_schema_fields = "\n".join(input_fields) if input_fields else "    pass"

    # Build the run method body
    if exec_type == "prompt":
        run_body = _build_prompt_run_body(execution, inputs)
    elif exec_type == "tool_call":
        run_body = _build_tool_call_run_body(execution)
    else:
        run_body = f'        raise NotImplementedError("Execution type \'{exec_type}\' requires manual implementation")'

    code = f'''"""
Auto-generated by ai-skills SDK
Skill: {skill["name"]} v{skill["version"]}
Source: {skill_path}

DO NOT EDIT — regenerate using:
    python exporters/langchain.py {skill_path}
"""

from typing import Optional, Type
from pydantic import BaseModel, Field
from langchain.tools import BaseTool


class {class_name}Input(BaseModel):
    """Input schema for {skill["name"]}"""
{input_schema_fields}


class {class_name}(BaseTool):
    """{description}"""
    
    name: str = "{skill_id}"
    description: str = "{description}"
    args_schema: Type[BaseModel] = {class_name}Input

    def _run(self, {", ".join(inp["name"] + ("" if inp.get("required") else f' = {repr(inp.get("default"))}') for inp in inputs)}) -> dict:
{run_body}

    async def _arun(self, **kwargs) -> dict:
        """Async version — delegates to sync for now."""
        return self._run(**kwargs)


# ── Usage ────────────────────────────────────────────────────────────────────
#
# from langchain.agents import initialize_agent, AgentType
# from langchain_openai import ChatOpenAI
#
# tool = {class_name}()
# llm = ChatOpenAI(model="gpt-4")
# agent = initialize_agent([tool], llm, agent=AgentType.OPENAI_FUNCTIONS)
#
# result = agent.run("Summarize this document: ...")
# ─────────────────────────────────────────────────────────────────────────────
'''
    if output_path:
        Path(output_path).write_text(code, encoding="utf-8")
        print(f"Exported to: {output_path}")
    else:
        print(code)

    return code


def _to_python_type(aiskills_type: str) -> str:
    mapping = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
        "file": "str",
        "image": "str",
        "any": "Any",
    }
    return mapping.get(aiskills_type, "str")


def _build_prompt_run_body(execution: dict, inputs: list) -> str:
    system_prompt = execution.get("system_prompt", "").strip()
    template = execution.get("prompt_template", "").strip()
    input_names = [inp["name"] for inp in inputs]

    format_kwargs = ", ".join(f'{n}={n}' for n in input_names)
    
    lines = [
        '        from langchain_openai import ChatOpenAI',
        '        from langchain.schema import HumanMessage, SystemMessage',
        '        ',
        '        llm = ChatOpenAI()',
        '        messages = []',
    ]

    if system_prompt:
        lines.append(f'        messages.append(SystemMessage(content="""{system_prompt}"""))')

    lines += [
        f'        prompt = """{template}"""',
        f'        formatted = prompt.format({format_kwargs})',
        '        messages.append(HumanMessage(content=formatted))',
        '        response = llm(messages)',
        '        return {"result": response.content}',
    ]

    return "\n".join(lines)


def _build_tool_call_run_body(execution: dict) -> str:
    endpoint = execution.get("endpoint", {})
    url = endpoint.get("url", "https://api.example.com")
    method = endpoint.get("method", "GET").lower()
    headers = endpoint.get("headers", {})
    params = endpoint.get("params", {})

    lines = [
        '        import requests',
        '        import os',
        '',
        f'        url = "{url}"',
    ]

    if headers:
        header_items = []
        for k, v in headers.items():
            # Replace {env.VAR} with os.environ.get("VAR")
            v_code = _resolve_env_refs(v)
            header_items.append(f'            "{k}": {v_code},')
        lines.append('        headers = {')
        lines.extend(header_items)
        lines.append('        }')
    else:
        lines.append('        headers = {}')

    if params:
        param_items = []
        for k, v in params.items():
            # Replace {input_name} with the function argument
            v_code = _resolve_input_refs(v)
            param_items.append(f'            "{k}": {v_code},')
        lines.append('        params = {')
        lines.extend(param_items)
        lines.append('        }')
    else:
        lines.append('        params = {}')

    lines += [
        f'        response = requests.{method}(url, headers=headers, params=params)',
        '        response.raise_for_status()',
        '        return response.json()',
    ]

    return '\n'.join(lines)


def _resolve_env_refs(value: str) -> str:
    """Replace {env.VAR_NAME} patterns with os.environ.get('VAR_NAME')."""
    import re
    pattern = r'\{env\.(\w+)\}'
    match = re.search(pattern, value)
    if match:
        var_name = match.group(1)
        return f'os.environ.get("{var_name}", "")'
    return repr(value)


def _resolve_input_refs(value: str) -> str:
    """Replace {input_name} patterns with the input variable reference."""
    import re
    pattern = r'^\{(\w+)\}$'
    match = re.match(pattern, value.strip())
    if match:
        return match.group(1)
    return repr(value)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export a skill.yaml to a LangChain Tool")
    parser.add_argument("skill_path", help="Path to skill.yaml")
    parser.add_argument("--output", "-o", help="Output Python file path")
    args = parser.parse_args()
    export_langchain(args.skill_path, args.output)
