"""
Auto-generated by ai-skills SDK
Skill: Document Summarizer v1.0.0
Source: skills\summarize-document\skill.yaml

DO NOT EDIT — regenerate using:
    python exporters/autogen.py skills\summarize-document\skill.yaml
"""

from typing import Any

from autogen_core.tools import FunctionTool


def summarize_document(document: str, max_words: int = 150, language: str = 'english') -> dict:
    """
    Summarizes a document into a concise summary and key bullet points. Works best on documents under 10,000 words.
    
    Args:
        document: The full text of the document to summarize (required)
        max_words: Maximum number of words in the summary (optional)
        language: Language for the output summary (optional)
    
    Returns:
        summary: Concise summary of the document
        key_points: 3 to 5 key takeaways from the document
    """
    import openai
    client = openai.OpenAI()
    messages = []
    messages.append({"role": "system", "content": """You are an expert summarizer. Be concise, accurate, and neutral.
Never add information not present in the original document."""})
    prompt = """Summarize the following document in under {max_words} words.
Write the summary in {language}.

Respond in exactly this format:
SUMMARY: [your summary here]
KEY_POINTS:
- [key point 1]
- [key point 2]
- [key point 3]

Document:
{document}"""
    formatted = prompt.format(document=document, max_words=max_words, language=language)
    messages.append({"role": "user", "content": formatted})
    response = client.chat.completions.create(model="gpt-4o", messages=messages)
    return {"result": response.choices[0].message.content}


# Register as an AutoGen FunctionTool
summarize_document_tool = FunctionTool(
    summarize_document,
    description="Summarizes a document into a concise summary and key bullet points. Works best on documents under 10,000 words.",
    name="summarize_document",
)


# ── Usage ────────────────────────────────────────────────────────────────────
#
# from autogen_agentchat.agents import AssistantAgent
# from autogen_ext.models.openai import OpenAIChatCompletionClient
#
# model_client = OpenAIChatCompletionClient(model="gpt-4o")
#
# agent = AssistantAgent(
#     name="assistant",
#     model_client=model_client,
#     tools=[summarize_document_tool],
# )
#
# import asyncio
# result = asyncio.run(agent.run(task="Use the summarize_document skill to ..."))
# ─────────────────────────────────────────────────────────────────────────────
