"""
Auto-generated by ai-skills SDK
Skill: Document Summarizer v1.0.0
Source: skills\summarize-document\skill.yaml

DO NOT EDIT — regenerate using:
    python exporters/langchain.py skills\summarize-document\skill.yaml
"""

from typing import Optional, Type
from pydantic import BaseModel, Field
from langchain.tools import BaseTool


class SummarizeDocumentToolInput(BaseModel):
    """Input schema for Document Summarizer"""
    document: str = Field(..., description="The full text of the document to summarize")
    max_words: int = Field(150, description="Maximum number of words in the summary")
    language: str = Field('english', description="Language for the output summary")


class SummarizeDocumentTool(BaseTool):
    """Summarizes a document into a concise summary and key bullet points. Works best on documents under 10,000 words."""
    
    name: str = "summarize_document"
    description: str = "Summarizes a document into a concise summary and key bullet points. Works best on documents under 10,000 words."
    args_schema: Type[BaseModel] = SummarizeDocumentToolInput

    def _run(self, document, max_words = 150, language = 'english') -> dict:
        from langchain_openai import ChatOpenAI
        from langchain.schema import HumanMessage, SystemMessage
        
        llm = ChatOpenAI()
        messages = []
        messages.append(SystemMessage(content="""You are an expert summarizer. Be concise, accurate, and neutral.
Never add information not present in the original document."""))
        prompt = """Summarize the following document in under {max_words} words.
Write the summary in {language}.

Respond in exactly this format:
SUMMARY: [your summary here]
KEY_POINTS:
- [key point 1]
- [key point 2]
- [key point 3]

Document:
{document}"""
        formatted = prompt.format(document=document, max_words=max_words, language=language)
        messages.append(HumanMessage(content=formatted))
        response = llm(messages)
        return {"result": response.content}

    async def _arun(self, **kwargs) -> dict:
        """Async version — delegates to sync for now."""
        return self._run(**kwargs)


# ── Usage ────────────────────────────────────────────────────────────────────
#
# from langchain.agents import initialize_agent, AgentType
# from langchain_openai import ChatOpenAI
#
# tool = SummarizeDocumentTool()
# llm = ChatOpenAI(model="gpt-4")
# agent = initialize_agent([tool], llm, agent=AgentType.OPENAI_FUNCTIONS)
#
# result = agent.run("Summarize this document: ...")
# ─────────────────────────────────────────────────────────────────────────────
