"""
Auto-generated by ai-skills SDK
Skill: Markdown to HTML Converter v1.0.0
Source: examples/markdown-to-html/skill.yaml

DO NOT EDIT — regenerate using:
    python exporters/langchain.py examples/markdown-to-html/skill.yaml
"""

from typing import Optional, Type
from pydantic import BaseModel, Field
from langchain.tools import BaseTool


class MarkdownToHtmlToolInput(BaseModel):
    """Input schema for Markdown to HTML Converter"""
    markdown: str = Field(..., description="The Markdown text to convert")


class MarkdownToHtmlTool(BaseTool):
    """Converts Markdown text to HTML. Supports headers, bold, italic, links, images, code blocks, blockquotes, unordered lists, ordered lists, and horizontal rules."""
    
    name: str = "markdown_to_html"
    description: str = "Converts Markdown text to HTML. Supports headers, bold, italic, links, images, code blocks, blockquotes, unordered lists, ordered lists, and horizontal rules."
    args_schema: Type[BaseModel] = MarkdownToHtmlToolInput

    def _run(self, markdown) -> dict:
        raise NotImplementedError("Execution type 'code' requires manual implementation")

    async def _arun(self, **kwargs) -> dict:
        """Async version — delegates to sync for now."""
        return self._run(**kwargs)


# ── Usage ────────────────────────────────────────────────────────────────────
#
# from langchain.agents import initialize_agent, AgentType
# from langchain_openai import ChatOpenAI
#
# tool = MarkdownToHtmlTool()
# llm = ChatOpenAI(model="gpt-4")
# agent = initialize_agent([tool], llm, agent=AgentType.OPENAI_FUNCTIONS)
#
# result = agent.run("Summarize this document: ...")
# ─────────────────────────────────────────────────────────────────────────────
